### ISSUE TITLE
cropping screen is limited to visible portion of the page

### ISSUE THREAD

**Issue by bhargav-garlapati** [Rykus0/nightwatch-visual-regression#17]
Hi Rykus0,

Is there any way to take the whole page screenshot instead of cropping only to the visible portion of the page in the browser?

Thanks.

**Comment by Rykus0** [comment]
This is the default behavior if you do not pass a selector.  If you do pass a selector, it will crop to that element's boundaries.

There is an issue with the Chrome webdriver that screenshots only return the visible viewport to begin with, so it is beyond the control of this plugin.

I have confirmed that I get a full page screenshot with PhantomJS, while Chrome returns only the viewport.

**Comment by Rykus0** [comment]
Also, check your configuration to see if you have set the value of defaultSelector.

**Comment by bhargav-garlapati** [comment]
Thanks for the reply, I was using chrome. Will update here with another browser! Thanks again.

**Comment by bhargav-garlapati** [comment]
Hi Rykus0, just tested it on phantom js and it works great!!
