### ISSUE TITLE
Error while using browser.assert.visualRegression('.selector'); - allElements.shift is not a function

### ISSUE THREAD

**Issue by drptbl** [Rykus0/nightwatch-visual-regression#7]
Hello,

Using newest Nightwatch.js:
`browser.assert.visualRegression('.site-nav');` command throws an error, while `browser.assert.visualRegression();` works properly. 

```
Running:  Main menu tests should check that site navigation has header with proper styles and url
Error while running getLocation command: allElements.shift is not a function
    at Object.cropElement (/js/assertions/visualRegression.js:17:10)
    at Object.<anonymous> (/js/assertions/visualRegression.js:186:37)
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/nightwatch/lib/api/client-commands.js:106:22
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/nightwatch/lib/index.js:422:11
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
Error while running getLocation command: allElements.shift is not a function
    at Object.cropElement (/js/assertions/visualRegression.js:17:10)
    at Object.<anonymous> (/js/assertions/visualRegression.js:186:37)
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/nightwatch/lib/api/client-commands.js:106:22
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/nightwatch/lib/index.js:422:11
    at /Users/jm/repos/kiln/entities-manager-e2e-tests/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Problem is exactly there:

```
    this.getLocation(selector, function(results){
        var origin = results.value;
```

`getLocation` throws an error.

Any suggestions? Looks like an issue with cropping or something related to this, because it occurs only when I want to screenshot chosen element.

Thanks in advance,
drptbl.

**Comment by Rykus0** [comment]
Thanks for pointing this out.  I'll take a look and let you know what I find.  My first guess is that `allElements` is null, probably because it didn't find any elements matching the selector.

**Comment by drptbl** [comment]
Hmm.. I will try to investigate this further over the weekend, but I'm sure that selector exists, because `hide` and `show` commands works properly (after doing a quick and simple fix for them - there was also an issue, will do a pull request at friday) for exactly the same selector. So I'm sure that issue exists in `visualRegression()` command, but I was not able to fix it by myself.

Still, when you said about `allElements`.. I will debug further and check what's happening :), thanks.

**Comment by Rykus0** [comment]
I was able to reproduce this issue while extending the functionality to page objects.  Until now, I haven't been using this with any selector, so I hadn't experienced it, and I didn't have the time/opportunity to test it with one.  I'll be working on this today and will hopefully have a fix soon.

**Comment by drptbl** [comment]
@Rykus0 Thanks for a fix. Will check it out :+1:!
