### ISSUE TITLE
`expected "0.1" but got: null` while screen differs.

### ISSUE THREAD

**Issue by drptbl** [Rykus0/nightwatch-visual-regression#9]
Hey @Rykus0,

Getting this error while screen differs from baseline:

```
✖ Visual Regression: Screen differs by 0.41% (see: visualregression/screenshots/failures/homePage/mainMenuSpec/chrome_51.0.2704.103_MAC/1680x1050/Check that menu exists on home page__body.diff.png)  - expected "0.1" but got: null
    at Object.module.exports.Check that menu exists on home page (/tests/homePage/mainMenuSpec.js:56:22)
    at Module.call (/tests/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /tests/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/tests/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/tests/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/tests/node_modules/q/q.js:796:13)
    at /tests/node_modules/q/q.js:556:49
    at runSingle (/tests/node_modules/q/q.js:137:13)
    at flush (/tests/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

`expected "0.1" but got: null`
instead of `null`, there should be a differ percentage, right?
so properly it should look like:
`expected "0.1" but got: 0.41`
in this case.

Tested on MAC OS, Nightwatch.js v`0.9.5`.

Cheers!

**Comment by Rykus0** [comment]
Yes, this has been there for a while.  Thanks for logging the issue.  I've been meaning to look into it...  It looks like it should be picking it up correctly (the actual is showing up in the other part of the message), but for some reason it's not.

**Comment by Rykus0** [comment]
Ok, it looks like this is due to how nightwatch handles assertions that define a failure function.  In this case, the "actual" value is set to null... not sure why they do that, and then also append a message that uses that value.  

in lib/core/assertion.js:

```
  if (typeof self.failure == 'function' && self.failure(result)) {
    passed = false;
    value = null;
  } else {
    value = self.value(result);
    passed = self.pass(value);
  }
```

I would think they should do the same they do with expected:

```
  var expected = typeof self.expected == 'function' ? self.expected() : self.expected;
```

Instead of opening a nightwatch issue - since they probably have a reason for this that I'm not seeing, I should be able to move the failure logic into the command function.
